import fs from 'fs'
import path from 'path'

const outDir = path.resolve(process.cwd(), 'build', 'dev')
fs.mkdirSync(outDir, { recursive: true })

function capitalizeTag(tag) {
    if (!tag || typeof tag !== 'string') return tag
    return tag[0].toUpperCase() + tag.slice(1)
}

function propToQml(key, value) {
    if (value === null || value === undefined) return ''
    // dotted keys like 'anchors.centerIn'
    if (key.indexOf('.') !== -1) {
        return `${key}: ${value}`
    }
    if (typeof value === 'string') {
        return `${key}: \"${value}\"`
    }
    if (typeof value === 'boolean' || typeof value === 'number') {
        return `${key}: ${value}`
    }
    if (typeof value === 'object') {
        // simple object -> nested block
        let entries = Object.entries(value).map(([k, v]) => `\n    ${k}: ${JSON.stringify(v)}`)
        return `${key}: {${entries.join('')}}`
    }
    return `${key}: ${JSON.stringify(value)}`
}

function renderVNode(vnode) {
    if (vnode == null) return ''
    if (typeof vnode === 'string' || typeof vnode === 'number') {
        // wrap raw strings into a Text
        return `Text { text: \"${vnode}\" }`
    }
    const type = capitalizeTag(vnode.type)
    const props = vnode.props || {}
    const attrs = []
    for (const k of Object.keys(props)) {
        if (k === 'children') continue
        attrs.push(propToQml(k, props[k]))
    }
    const children = (vnode.children || []).map(renderVNode).filter(Boolean)
    const inner = [attrs.filter(Boolean).join('; '), ...children].filter(Boolean).join('\n    ')
    return `${type} { ${inner ? '\n    ' + inner + '\n' : ''}}`
}

async function emit() {
    try {
        const mod = await import(path.join(process.cwd(), 'src', 'index.tsx'))

        // try common export names; prefer a component function that returns a vnode
        let comp = mod.Example || mod.default || mod.App || (mod && mod.init && (() => ({ type: 'Rectangle', props: { width: 120, height: 40, color: '#6272a4' }, children: [] })))

        let vnode = null
        if (typeof comp === 'function') {
            vnode = comp()
        } else if (comp && typeof comp === 'object') {
            vnode = comp
        }

        let qml = ''
        if (vnode) {
            qml = renderVNode(vnode)
        } else {
            qml = 'Rectangle { width: 220; height: 60; color: "#6272a4"; Text { anchors.centerIn: parent; text: "TSX UI (dev)"; color: "white" } }'
        }

        const content = `// Generated by dev_emit.mjs from TSX
function createFrontend(parent) {
        var qml = ${JSON.stringify('import QtQuick 2.15; ' + qml)};
        return Qt.createQmlObject(qml, parent);
}
`

        const outPath = path.join(outDir, 'frontend_vm.js')
        fs.writeFileSync(outPath, content, { encoding: 'utf8' })
        console.log('Wrote dev bridge to', outPath)
    } catch (e) {
        console.error('emit failed:', e)
        process.exitCode = 1
    }
}

emit()
